AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance creation"
Parameters:
  InstanceType: 
    Description: "EC2 instance type"
    Type: "String"
    Default: "t2.nano"
    AllowedValues: [
        "t1.micro",
        "t2.micro",
        "t2.nano",
        "t2.small"
    ]
    ConstraintDescription: "must be a valid EC2 instance type"
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: PV64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64      
  AWSRegionArch2AMI:
    us-east-1:
      PV64: ami-2a69aa47
      HVM64: ami-6869aa05
      HVMG2: ami-61e27177  
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType:
        Ref: "InstanceType"
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch        